os: linux
dist: focal
language: python
cache: pip
branches:
  only:
    - master

jobs:
  include:
    - python: 3.7
      env: TOXENV=alpine TEST_ALPINE=1

install:
  - pip install tox
script:
  - tox
after_success:
  - pip install coveralls
  - coveralls
